version: '3.8'

services:
  api-ddd:
    build: .
    environment:
      MOOC_HOST: 0.0.0.0
      MOOC_DBHOST: mysql
    ports:
      - 8080:8080

  mysql:
    image: mysql:8.0.22
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: api-ddd
      MYSQL_USER: api-ddd
      MYSQL_PASSWORD: api-ddd
      MYSQL_ROOT_PASSWORD: api-ddd

volumes:
  mysql_data: